 <div class="container">
            	<div class="inner">
                	<div class="extra-wrap">
                        <h1><a href="index.php">Visalia Medical Clinic</a></h1>
                        <div class="menu_block">
                          <div class="wrapper">
                            <ul class="login_panel">
							  
							 
							 
							   
                          <li><a href="index.php">Home</a></li>
						    <li><a href="employment.php">Employment</a></li>
                              <li><a href="aboutus.php">Contact us</a></li>
							      <li><a href="billpay.php">Pay bill online</a></li>
                            </ul>
                          </div>
                          <nav>
                            <ul class="sf-menu">
							
						
							
                                <li class="active"><a href="#">FollowMyHealth</a>
								<ul>
                                         <li><a href="portal.php">About Follow My Health</a></li>
										 <li><a href="http://support.followmyhealth.com/customer/portal/topics/506281-frequently-asked-questions/articles"target="_blank">FAQ</a></li>
										 <li><a href="http://visaliamedicalclinic.followmyhealth.com"target="_blank">Login/Create Account</a></li>
										<li><a href="billpay.php">Pay bill online</a></li>
										 <li><a href="http://visaliamedicalclinic.com/fmhproxyrequest/"target="_blank">Request Proxy Access</a></li>
										<li><a href="followmyhealthsupport.php">Technical Support</a></li>
										
									
                                       
                                    </ul>
                              </li>
								
                              <li><a href="#">For Patients</a>
                                	<ul>
                                
								<li><a href="advanced_directive.php">Advanced Directive</a></li>
								
								<li><a href="findadoc.php">Find a provider</a></li>
										<li><a href="newsevents.php">News/Events</a></li>
										<li><a href="guide.php">Patient Guide</a></li>
                                    </ul>
                              </li>
                                <li class="active"><a href="#">For Doctors</a>
                                
                             
                                <ul>
                                  
                                      <li><a href="recruitment.php">Recruitment</a></li>
                                  </ul>
                              </li>
							  
							  
                                <li><a href="#">Services</a>
                                <ul>
								 <li><a href="http://www.vmcallergyandsinus.com/" target="_blank">Allergy and Sinus Center</a></li>
                                 <li><a href="diabetes.php">Diabetes</a></li>
								  <li><a href="radiology_department_highlights.php" target="_blank">Imaging</a></li>
								  <li><a href=" http://www.mihalcinorthopedics.com/" target="_blank">Orthopedics </a></li>
								  	<li><a href="pediatrics.php">Pediatrics</a></li>
                                    <li><a href="http://www.vmcpt.com"target="_blank">Physical Therapy</a></li>
									<li><a href="http://www.drlechtman.com">Plastic Surgery</a></li>
									  <li><a href="http://visaliafootdoctor.com" target="_blank">Podiatry</a></li>
									  <li><a href="quickcare.php">QuickCare walk-in</a></li>
								<li><a href="http://www.vmcsleepdisorders.com" target="_blank">Sleep Disorders Center</a></li>
									 <li><a href="http://www.drlechtman.com/landing-page">The Aesthetic Center<br>Before and After Album</a></li>
                                  <li><a href="thewellnesscenter.php" target="_blank">Wellness Center</a></li>
								</ul>
                              </li>
                                
                                
                                <li><a href="#">About us</a>
								<ul>
								  <li><a href="aboutus.php">Contact us</a></li>
							  <li><a href="employment.php">Employment</a></li>
							</li>
                        </nav>
                        </div>
                        <div class="clear"></div>
                    </div>
              </div>
            </div>